# Generated by Django 5.2.5 on 2025-12-24 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('all_day', models.BooleanField(default=False, verbose_name='All day')),
                ('time_start', models.DateTimeField(verbose_name='Start time')),
                ('time_end', models.DateTimeField(verbose_name='End time')),
                ('repeat', models.TextField(blank=True, null=True, verbose_name='Repeat')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Is cancelled')),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=50, verbose_name='Timezone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['time_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model name')),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('changes', models.JSONField(default=dict, verbose_name='Changes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendarapp.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField(verbose_name='Value')),
                ('unit', models.CharField(choices=[('m', 'Minutes'), ('h', 'Hours'), ('d', 'Days'), ('w', 'Weeks')], default='m', max_length=1, verbose_name='Unit')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='calendarapp.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event alert',
                'verbose_name_plural': 'Event alerts',
            },
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='calendarapp.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event invite',
                'verbose_name_plural': 'Event invites',
            },
        ),
        migrations.CreateModel(
            name='ParsedEventDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField(verbose_name='Original text')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Language')),
                ('intent', models.CharField(max_length=50, verbose_name='Intent')),
                ('extracted_data', models.JSONField(default=dict, verbose_name='Extracted data')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Parsed event draft',
                'verbose_name_plural': 'Parsed event drafts',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'time_start'], name='calendarapp_user_id_4e2707_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['time_start', 'time_end'], name='calendarapp_time_st_bb6353_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventinvite',
            unique_together={('event', 'email')},
        ),
    ]
