# Generated by Django 5.2.5 on 2025-08-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status_uz',
        ),
    ]
