# Generated by Django 5.2.5 on 2025-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_job_en_remove_user_job_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GRADUATED', 'Graduated'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='GRADUATED', max_length=20, verbose_name='role'),
        ),
    ]
