# Generated by Django 5.2.5 on 2025-12-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='video',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
